# Load the library
library(stats)

# read in the dataset
df1 <- read.csv('data/math scores.csv')
# df1 <- read.csv('../data/math scores.csv')   # backup version

## If you encountered problems here, pls feel free to contact your instructors

# statistic for the original sample
original <- mean(df1[11:20,2]) - mean(df1[1:10,2])
original

# Slide 11: Some Preparations in R

treatment <- df1$treatment
treatment
outcome <- df1$outcome
outcome

# Slide 12: "Sample()" Function

set.seed(123)
sample(1:5, size = 1)
sample(1:5, size = 5, replace=FALSE)

# Slide 13: Generating a Permutation Sample

# the code reassigns the group order of all students 
treatment_p <- sample(treatment, size= length(treatment), replace=FALSE)
treatment_p

# the following code generates a vector of TRUE or FALSE, indicating 
# whether the student belongs to Group B under the new assignment
treatment_p == "b"

# the code generates a vector of scores only for the students who belong 
# to group B under the new assignment
outcome[treatment_p == "b"]

# similarly, for group A
outcome[treatment_p == "a"]

# calculate the test statistic for the new permutation sample
mean(outcome[treatment_p == "b"]) - mean(outcome[treatment_p == "a"])

# Slide 14: "for loop"

sum <- 0
for (i in 1:2) {
  sum <- sum + i
}
sum

# Slide 15: Use "for loop" to Generate Multiple Permutation Samples

size <- 10000
perm_dist <- rep(0, size)  # a vector with purely zero values of size 10,000 

# for reproducibility of results
set.seed(123)

for(i in 1:size){
  # Take permutation sample, without replacement
  treatment_p <- sample(treatment, size= length(treatment), replace=FALSE)
  # For each permutation sample, calculate the statistic
  perm_dist[i] <- mean(outcome[treatment_p == "b"]) - 
    mean(outcome[treatment_p == "a"]) 
}

# Slide 16: Generate the Histogram of all Test Statistics

hist(perm_dist)

# Slide 19: Generate the Histogram of all Test Statistics

# a simplified version (as the coloring part is a bit complicated)
hist(perm_dist, main="Permutation Distribution", xlab='Test Statistic',  las=1,  cex.lab = 1.5,  cex.axis = 1.2, cex.main = 2)
abline(v=original, lty = 2, lwd = 3, col="red")
abline(v=-original, lty = 2, lwd = 3, col="red")

# Slide 20: Calculate p-value

# two tailed p-value = 0.0762
pvalue <- mean(abs(perm_dist) >= abs(original))
pvalue

head(abs(perm_dist) >= abs(original)) # check the first few observations

# Slide 21: Define a Function 

# it is the same one used under the for-loop
permutation.test <- function(treatment, outcome){
    # Generate a permutation sample
    treatment_p <- sample(treatment, size= length(treatment), replace=FALSE)
    # Calculate the test statistic for the permutation sample
   mean(outcome[treatment_p == "b"]) - 
                          mean(outcome[treatment_p == "a"]) 
  }

# Slide 22: Use the "replicate()" Function to Run Multiple Simulations

set.seed(123) 
test <- replicate(10000, permutation.test(treatment, outcome))

hist(test) # generate the histogram of all test statistics

# calculate the proportion of test statistics that are at least 
# as extreme as the observed one
mean(abs(test) >= abs(original))

# the p-value, by the replicate() function, is 0.0762, which coincides with 
# that generated by the for-loop method
# So, "for-loop" and "replicate()" are equivalent.

# Slide 24: Compare the p-values

# p-value from t.test is 0.0769
t.test(outcome~treatment, alternative = "two.sided", 
       paired=F, var.equal=T, data = df1)  


#-------------------- Optional Practice Session -----------------------

# Generate the boxplots for the new permutation sample
# You can select the codes below, and press "control + enter" to run 
# multiple simulations. (with different permutation samples)

par(mfrow=c(1,2)) # this is to show two plots in one row

# permutate the group order to generate the permutation sample
treatment_p <- sample(treatment, size= length(treatment), replace=FALSE)

# the boxplot of the original sample
boxplot(outcome~treatment, data = df1, ylab="scores", 
        xlab="Group",main="Original Sample")

# generate the data frame for the new permutation sample
perm_sample <- data.frame(treatment = treatment_p, outcome = outcome)

# it is clear that this is a new sample, and the mean score of Group A 
# is likely higher. 
boxplot(outcome~treatment, data = perm_sample, ylab="scores", 
        xlab="Group",main="Permutation Sample")

par(mfrow=c(1,1)) # reset to the default setting